// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="pixel_pack_pixel_pack,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=7.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.566000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=829,HLS_SYN_LUT=1015,HLS_VERSION=2020_2}" *)

module pixel_pack (
        ap_clk,
        ap_rst_n,
        stream_in_24_TDATA,
        stream_in_24_TVALID,
        stream_in_24_TREADY,
        stream_in_24_TKEEP,
        stream_in_24_TSTRB,
        stream_in_24_TUSER,
        stream_in_24_TLAST,
        stream_out_32_TDATA,
        stream_out_32_TVALID,
        stream_out_32_TREADY,
        stream_out_32_TKEEP,
        stream_out_32_TSTRB,
        stream_out_32_TUSER,
        stream_out_32_TLAST,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP
);

parameter    ap_ST_fsm_state1 = 19'd1;
parameter    ap_ST_fsm_state2 = 19'd2;
parameter    ap_ST_fsm_pp0_stage0 = 19'd4;
parameter    ap_ST_fsm_pp0_stage1 = 19'd8;
parameter    ap_ST_fsm_state6 = 19'd16;
parameter    ap_ST_fsm_pp1_stage0 = 19'd32;
parameter    ap_ST_fsm_pp1_stage1 = 19'd64;
parameter    ap_ST_fsm_pp2_stage0 = 19'd128;
parameter    ap_ST_fsm_pp2_stage1 = 19'd256;
parameter    ap_ST_fsm_pp2_stage2 = 19'd512;
parameter    ap_ST_fsm_pp2_stage3 = 19'd1024;
parameter    ap_ST_fsm_state15 = 19'd2048;
parameter    ap_ST_fsm_pp3_stage0 = 19'd4096;
parameter    ap_ST_fsm_state18 = 19'd8192;
parameter    ap_ST_fsm_pp4_stage0 = 19'd16384;
parameter    ap_ST_fsm_pp4_stage1 = 19'd32768;
parameter    ap_ST_fsm_pp4_stage2 = 19'd65536;
parameter    ap_ST_fsm_pp4_stage3 = 19'd131072;
parameter    ap_ST_fsm_state26 = 19'd262144;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [23:0] stream_in_24_TDATA;
input   stream_in_24_TVALID;
output   stream_in_24_TREADY;
input  [2:0] stream_in_24_TKEEP;
input  [2:0] stream_in_24_TSTRB;
input  [0:0] stream_in_24_TUSER;
input  [0:0] stream_in_24_TLAST;
output  [31:0] stream_out_32_TDATA;
output   stream_out_32_TVALID;
input   stream_out_32_TREADY;
output  [3:0] stream_out_32_TKEEP;
output  [3:0] stream_out_32_TSTRB;
output  [0:0] stream_out_32_TUSER;
output  [0:0] stream_out_32_TLAST;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;

 reg    ap_rst_n_inv;
wire   [31:0] mode;
reg   [31:0] mode_0_data_reg;
reg    mode_0_vld_reg;
reg    mode_0_ack_out;
wire   [7:0] alpha;
reg   [7:0] alpha_0_data_reg;
reg    alpha_0_vld_reg;
reg    alpha_0_ack_out;
reg    stream_in_24_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [18:0] ap_CS_fsm;
wire    ap_CS_fsm_pp4_stage0;
reg    ap_enable_reg_pp4_iter0;
wire    ap_block_pp4_stage0;
reg   [0:0] ap_phi_mux_delayed_last_phi_fu_413_p4;
reg   [0:0] ap_phi_mux_last_phi_fu_426_p4;
wire    ap_CS_fsm_pp4_stage1;
wire    ap_block_pp4_stage1;
reg   [0:0] delayed_last_reg_409;
reg   [0:0] last_2_0_reg_434;
wire    ap_CS_fsm_pp4_stage2;
wire    ap_block_pp4_stage2;
reg   [0:0] last_2_1_reg_478;
wire    ap_CS_fsm_pp4_stage3;
wire    ap_block_pp4_stage3;
reg   [0:0] last_2_2_reg_522;
wire    ap_CS_fsm_pp3_stage0;
reg    ap_enable_reg_pp3_iter0;
wire    ap_block_pp3_stage0;
wire    ap_CS_fsm_pp2_stage0;
reg    ap_enable_reg_pp2_iter0;
wire    ap_block_pp2_stage0;
reg   [0:0] ap_phi_mux_delayed_last_1_phi_fu_213_p4;
reg   [0:0] ap_phi_mux_last_4_phi_fu_226_p4;
wire    ap_CS_fsm_pp2_stage1;
wire    ap_block_pp2_stage1;
reg   [0:0] delayed_last_1_reg_209;
reg   [0:0] last_6_0_reg_234;
wire    ap_CS_fsm_pp2_stage2;
wire    ap_block_pp2_stage2;
reg   [0:0] last_6_1_reg_268;
wire    ap_CS_fsm_pp2_stage3;
wire    ap_block_pp2_stage3;
reg   [0:0] last_6_2_reg_301;
wire    ap_CS_fsm_pp1_stage0;
reg    ap_enable_reg_pp1_iter0;
wire    ap_block_pp1_stage0;
wire    ap_CS_fsm_pp1_stage1;
wire    ap_block_pp1_stage1;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1;
reg    stream_out_32_TDATA_blk_n;
reg   [0:0] last_reg_421;
reg    ap_enable_reg_pp4_iter1;
reg   [0:0] last_reg_421_pp4_iter1_reg;
reg    ap_enable_reg_pp3_iter1;
reg   [0:0] last_4_reg_221;
reg    ap_enable_reg_pp2_iter1;
reg    ap_enable_reg_pp1_iter1;
reg    ap_enable_reg_pp0_iter1;
reg   [31:0] data_V_8_3_reg_332;
reg   [0:0] last_6_3_reg_359;
reg    ap_predicate_op183_read_state19;
reg    ap_block_state19_pp4_stage0_iter0;
reg    ap_block_state23_pp4_stage0_iter1;
reg    ap_block_state23_io;
reg    ap_block_pp4_stage0_11001;
reg    ap_predicate_op197_read_state20;
reg    ap_block_state20_pp4_stage1_iter0;
reg    ap_block_state24_pp4_stage1_iter1;
reg    ap_block_state24_io;
reg    ap_block_pp4_stage1_11001;
reg   [3:0] has_user_V_3_3_reg_563;
reg   [3:0] has_last_V_3_3_reg_575;
reg   [95:0] buffer_V_3_3_reg_587;
reg   [0:0] last_2_3_reg_599;
reg   [7:0] alpha_read_reg_1073;
wire    ap_CS_fsm_state2;
wire   [31:0] grp_read_fu_156_p2;
reg   [0:0] empty_38_reg_1082_3;
reg    ap_block_state3_pp0_stage0_iter0;
reg    ap_block_state5_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [7:0] grp_fu_615_p4;
reg   [7:0] p_Result_s_40_reg_1087;
wire   [7:0] grp_fu_625_p4;
reg   [7:0] p_Result_5_reg_1092;
wire   [7:0] trunc_ln674_fu_653_p1;
reg   [7:0] trunc_ln674_reg_1097;
wire   [0:0] grp_fu_635_p1;
reg    ap_block_state4_pp0_stage1_iter0;
reg    ap_block_pp0_stage1_11001;
wire   [0:0] or_ln107_fu_664_p2;
wire   [31:0] p_Result_15_fu_721_p5;
reg   [0:0] empty_36_reg_1117_3;
reg    ap_block_state7_pp1_stage0_iter0;
reg    ap_block_state9_pp1_stage0_iter1;
reg    ap_block_pp1_stage0_11001;
wire   [15:0] trunc_ln215_fu_733_p1;
reg   [15:0] trunc_ln215_reg_1122;
reg    ap_block_state8_pp1_stage1_iter0;
reg    ap_block_pp1_stage1_11001;
wire   [0:0] or_ln90_fu_744_p2;
wire   [31:0] p_Result_36_1_fu_755_p3;
reg    ap_predicate_op111_read_state10;
reg    ap_block_state10_pp2_stage0_iter0;
reg    ap_block_state14_pp2_stage0_iter1;
reg    ap_block_state14_io;
reg    ap_block_pp2_stage0_11001;
wire   [31:0] p_Result_11_fu_767_p5;
wire   [0:0] or_ln70_fu_783_p2;
reg    ap_predicate_op123_read_state11;
reg    ap_block_state11_pp2_stage1_iter0;
reg    ap_block_pp2_stage1_11001;
wire   [31:0] p_Result_34_1_fu_793_p5;
wire   [0:0] or_ln70_1_fu_809_p2;
reg    ap_predicate_op135_read_state12;
reg    ap_block_state12_pp2_stage2_iter0;
reg    ap_block_pp2_stage2_11001;
wire   [31:0] p_Result_34_2_fu_819_p5;
reg    ap_block_state16_pp3_stage0_iter0;
reg    ap_block_state17_pp3_stage0_iter1;
reg    ap_block_pp3_stage0_11001;
wire   [31:0] p_Result_14_fu_859_p3;
wire   [95:0] p_Result_s_fu_867_p5;
wire   [3:0] tmp_fu_879_p4;
wire   [3:0] tmp_1_fu_889_p4;
wire   [95:0] p_Result_1_fu_899_p5;
wire   [3:0] tmp_2_fu_911_p4;
wire   [3:0] tmp_3_fu_921_p4;
wire   [95:0] p_Result_2_fu_931_p5;
reg    ap_predicate_op210_read_state21;
reg    ap_block_state21_pp4_stage2_iter0;
reg    ap_block_state25_pp4_stage2_iter1;
reg    ap_block_state25_io;
reg    ap_block_pp4_stage2_11001;
wire   [3:0] tmp_4_fu_943_p4;
wire   [3:0] tmp_5_fu_953_p4;
wire   [31:0] trunc_ln674_6_fu_998_p1;
reg    ap_predicate_op223_read_state22;
reg    ap_predicate_op239_write_state22;
reg    ap_block_state22_pp4_stage3_iter0;
reg    ap_block_state22_io;
reg    ap_block_pp4_stage3_11001;
reg   [31:0] p_Result_28_1_reg_1247;
reg   [0:0] p_Result_29_1_reg_1252;
reg   [0:0] p_Result_30_1_reg_1257;
reg   [31:0] p_Result_28_2_reg_1262;
reg   [0:0] p_Result_29_2_reg_1267;
reg   [0:0] p_Result_30_2_reg_1272;
reg    ap_block_pp0_stage1_subdone;
reg    ap_condition_pp0_flush_enable;
reg    ap_block_pp0_stage0_subdone;
reg    ap_block_pp1_stage1_subdone;
reg    ap_condition_pp1_flush_enable;
reg    ap_block_pp1_stage0_subdone;
reg    ap_block_pp2_stage0_subdone;
reg    ap_condition_pp2_exit_iter0_state10;
reg    ap_predicate_op147_read_state13;
reg    ap_predicate_op159_write_state13;
reg    ap_block_state13_pp2_stage3_iter0;
reg    ap_block_state13_io;
reg    ap_block_pp2_stage3_subdone;
reg    ap_block_pp3_stage0_subdone;
reg    ap_condition_pp3_flush_enable;
reg    ap_block_pp4_stage0_subdone;
reg    ap_condition_pp4_exit_iter0_state19;
reg    ap_block_pp4_stage3_subdone;
reg    ap_block_pp4_stage2_subdone;
wire   [0:0] ap_phi_reg_pp2_iter0_last_6_0_reg_234;
reg   [31:0] ap_phi_reg_pp2_iter0_data_V_8_0_reg_245;
reg   [0:0] ap_phi_reg_pp2_iter0_user_6_0_reg_256;
wire   [0:0] ap_phi_reg_pp2_iter0_last_6_1_reg_268;
reg   [31:0] ap_phi_reg_pp2_iter0_data_V_8_1_reg_279;
reg   [0:0] ap_phi_reg_pp2_iter0_user_6_1_reg_290;
wire   [0:0] ap_phi_reg_pp2_iter0_last_6_2_reg_301;
reg   [31:0] ap_phi_reg_pp2_iter0_data_V_8_2_reg_312;
reg    ap_block_pp2_stage3_11001;
reg   [0:0] ap_phi_reg_pp2_iter0_user_6_2_reg_322;
reg   [31:0] ap_phi_mux_data_V_8_3_phi_fu_337_p4;
wire   [31:0] p_Result_34_3_fu_846_p5;
wire   [31:0] ap_phi_reg_pp2_iter0_data_V_8_3_reg_332;
reg   [0:0] ap_phi_mux_user_6_3_phi_fu_350_p4;
wire   [0:0] or_ln70_2_fu_835_p2;
wire   [0:0] ap_phi_reg_pp2_iter0_user_6_3_reg_346;
reg   [0:0] ap_phi_mux_last_6_3_phi_fu_364_p4;
wire   [0:0] ap_phi_reg_pp2_iter0_last_6_3_reg_359;
wire   [0:0] ap_phi_reg_pp4_iter0_last_2_0_reg_434;
reg   [3:0] ap_phi_reg_pp4_iter0_has_user_V_3_0_reg_445;
reg   [3:0] ap_phi_reg_pp4_iter0_has_last_V_3_0_reg_456;
reg   [95:0] ap_phi_reg_pp4_iter0_buffer_V_3_0_reg_467;
wire   [0:0] ap_phi_reg_pp4_iter0_last_2_1_reg_478;
reg   [3:0] ap_phi_reg_pp4_iter0_has_user_V_3_1_reg_489;
reg   [3:0] ap_phi_reg_pp4_iter0_has_last_V_3_1_reg_500;
reg   [95:0] ap_phi_reg_pp4_iter0_buffer_V_3_1_reg_511;
wire   [0:0] ap_phi_reg_pp4_iter0_last_2_2_reg_522;
reg   [3:0] ap_phi_reg_pp4_iter0_has_user_V_3_2_reg_533;
reg   [3:0] ap_phi_reg_pp4_iter0_has_last_V_3_2_reg_543;
reg   [95:0] ap_phi_reg_pp4_iter0_buffer_V_3_2_reg_553;
reg   [3:0] ap_phi_mux_has_user_V_3_3_phi_fu_567_p4;
wire   [3:0] tmp_6_fu_976_p4;
wire   [3:0] ap_phi_reg_pp4_iter0_has_user_V_3_3_reg_563;
reg   [3:0] ap_phi_mux_has_last_V_3_3_phi_fu_579_p4;
wire   [3:0] tmp_7_fu_987_p4;
wire   [3:0] ap_phi_reg_pp4_iter0_has_last_V_3_3_reg_575;
reg   [95:0] ap_phi_mux_buffer_V_3_3_phi_fu_591_p4;
wire   [95:0] p_Result_3_fu_963_p5;
wire   [95:0] ap_phi_reg_pp4_iter0_buffer_V_3_3_reg_587;
wire   [0:0] ap_phi_reg_pp4_iter0_last_2_3_reg_599;
reg    ap_block_pp0_stage1_01001;
reg    ap_block_pp1_stage1_01001;
reg    ap_block_pp2_stage3_01001;
reg    ap_block_pp3_stage0_01001;
reg    ap_block_pp4_stage3_01001;
reg    ap_block_pp4_stage0_01001;
reg    ap_block_pp4_stage1_01001;
wire   [8:0] zext_ln358_1_fu_674_p1;
wire   [8:0] zext_ln358_fu_671_p1;
wire   [8:0] zext_ln358_3_fu_687_p1;
wire   [8:0] zext_ln358_2_fu_684_p1;
wire   [8:0] out_c1_V_fu_678_p2;
wire   [8:0] out_c2_V_fu_691_p2;
wire   [7:0] p_Result_9_fu_711_p4;
wire   [7:0] trunc_ln674_1_fu_707_p1;
wire   [7:0] p_Result_8_fu_697_p4;
wire   [15:0] trunc_ln215_1_fu_751_p1;
wire   [7:0] trunc_ln674_2_fu_763_p1;
wire   [7:0] trunc_ln674_3_fu_789_p1;
wire   [7:0] trunc_ln674_4_fu_815_p1;
wire   [7:0] trunc_ln674_5_fu_842_p1;
wire    ap_CS_fsm_state6;
wire    regslice_both_stream_out_32_V_data_V_U_apdone_blk;
reg   [18:0] ap_NS_fsm;
reg    ap_block_pp2_stage1_subdone;
reg    ap_block_pp2_stage2_subdone;
reg    ap_block_pp4_stage1_subdone;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
reg    ap_idle_pp2;
wire    ap_enable_pp2;
reg    ap_idle_pp3;
wire    ap_enable_pp3;
reg    ap_idle_pp4;
wire    ap_enable_pp4;
wire    regslice_both_stream_in_24_V_data_V_U_apdone_blk;
wire   [23:0] stream_in_24_TDATA_int_regslice;
wire    stream_in_24_TVALID_int_regslice;
reg    stream_in_24_TREADY_int_regslice;
wire    regslice_both_stream_in_24_V_data_V_U_ack_in;
wire    regslice_both_stream_in_24_V_keep_V_U_apdone_blk;
wire   [2:0] stream_in_24_TKEEP_int_regslice;
wire    regslice_both_stream_in_24_V_keep_V_U_vld_out;
wire    regslice_both_stream_in_24_V_keep_V_U_ack_in;
wire    regslice_both_stream_in_24_V_strb_V_U_apdone_blk;
wire   [2:0] stream_in_24_TSTRB_int_regslice;
wire    regslice_both_stream_in_24_V_strb_V_U_vld_out;
wire    regslice_both_stream_in_24_V_strb_V_U_ack_in;
wire    regslice_both_stream_in_24_V_user_V_U_apdone_blk;
wire   [0:0] stream_in_24_TUSER_int_regslice;
wire    regslice_both_stream_in_24_V_user_V_U_vld_out;
wire    regslice_both_stream_in_24_V_user_V_U_ack_in;
wire    regslice_both_stream_in_24_V_last_V_U_apdone_blk;
wire   [0:0] stream_in_24_TLAST_int_regslice;
wire    regslice_both_stream_in_24_V_last_V_U_vld_out;
wire    regslice_both_stream_in_24_V_last_V_U_ack_in;
reg   [31:0] stream_out_32_TDATA_int_regslice;
reg    stream_out_32_TVALID_int_regslice;
wire    stream_out_32_TREADY_int_regslice;
wire    regslice_both_stream_out_32_V_data_V_U_vld_out;
wire    regslice_both_stream_out_32_V_keep_V_U_apdone_blk;
wire    regslice_both_stream_out_32_V_keep_V_U_ack_in_dummy;
wire    regslice_both_stream_out_32_V_keep_V_U_vld_out;
wire    regslice_both_stream_out_32_V_strb_V_U_apdone_blk;
wire    regslice_both_stream_out_32_V_strb_V_U_ack_in_dummy;
wire    regslice_both_stream_out_32_V_strb_V_U_vld_out;
wire    regslice_both_stream_out_32_V_user_V_U_apdone_blk;
reg   [0:0] stream_out_32_TUSER_int_regslice;
wire    regslice_both_stream_out_32_V_user_V_U_ack_in_dummy;
wire    regslice_both_stream_out_32_V_user_V_U_vld_out;
wire    regslice_both_stream_out_32_V_last_V_U_apdone_blk;
reg   [0:0] stream_out_32_TLAST_int_regslice;
wire    regslice_both_stream_out_32_V_last_V_U_ack_in_dummy;
wire    regslice_both_stream_out_32_V_last_V_U_vld_out;
reg    ap_condition_1536;
reg    ap_condition_1540;
reg    ap_condition_1545;
reg    ap_condition_1549;
reg    ap_condition_1553;
reg    ap_condition_1558;
reg    ap_condition_876;
reg    ap_condition_820;
reg    ap_condition_843;
reg    ap_condition_850;
reg    ap_condition_863;
reg    ap_condition_567;
reg    ap_condition_795;
reg    ap_condition_806;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 mode_0_data_reg = 32'd0;
#0 mode_0_vld_reg = 1'b0;
#0 alpha_0_data_reg = 8'd0;
#0 alpha_0_vld_reg = 1'b0;
#0 ap_CS_fsm = 19'd1;
#0 ap_enable_reg_pp4_iter0 = 1'b0;
#0 ap_enable_reg_pp3_iter0 = 1'b0;
#0 ap_enable_reg_pp2_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp4_iter1 = 1'b0;
#0 ap_enable_reg_pp3_iter1 = 1'b0;
#0 ap_enable_reg_pp2_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

pixel_pack_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .mode(mode),
    .alpha(alpha)
);

pixel_pack_regslice_both #(
    .DataWidth( 24 ))
regslice_both_stream_in_24_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_24_TDATA),
    .vld_in(stream_in_24_TVALID),
    .ack_in(regslice_both_stream_in_24_V_data_V_U_ack_in),
    .data_out(stream_in_24_TDATA_int_regslice),
    .vld_out(stream_in_24_TVALID_int_regslice),
    .ack_out(stream_in_24_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_24_V_data_V_U_apdone_blk)
);

pixel_pack_regslice_both #(
    .DataWidth( 3 ))
regslice_both_stream_in_24_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_24_TKEEP),
    .vld_in(stream_in_24_TVALID),
    .ack_in(regslice_both_stream_in_24_V_keep_V_U_ack_in),
    .data_out(stream_in_24_TKEEP_int_regslice),
    .vld_out(regslice_both_stream_in_24_V_keep_V_U_vld_out),
    .ack_out(stream_in_24_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_24_V_keep_V_U_apdone_blk)
);

pixel_pack_regslice_both #(
    .DataWidth( 3 ))
regslice_both_stream_in_24_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_24_TSTRB),
    .vld_in(stream_in_24_TVALID),
    .ack_in(regslice_both_stream_in_24_V_strb_V_U_ack_in),
    .data_out(stream_in_24_TSTRB_int_regslice),
    .vld_out(regslice_both_stream_in_24_V_strb_V_U_vld_out),
    .ack_out(stream_in_24_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_24_V_strb_V_U_apdone_blk)
);

pixel_pack_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_in_24_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_24_TUSER),
    .vld_in(stream_in_24_TVALID),
    .ack_in(regslice_both_stream_in_24_V_user_V_U_ack_in),
    .data_out(stream_in_24_TUSER_int_regslice),
    .vld_out(regslice_both_stream_in_24_V_user_V_U_vld_out),
    .ack_out(stream_in_24_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_24_V_user_V_U_apdone_blk)
);

pixel_pack_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_in_24_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_24_TLAST),
    .vld_in(stream_in_24_TVALID),
    .ack_in(regslice_both_stream_in_24_V_last_V_U_ack_in),
    .data_out(stream_in_24_TLAST_int_regslice),
    .vld_out(regslice_both_stream_in_24_V_last_V_U_vld_out),
    .ack_out(stream_in_24_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_24_V_last_V_U_apdone_blk)
);

pixel_pack_regslice_both #(
    .DataWidth( 32 ))
regslice_both_stream_out_32_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_out_32_TDATA_int_regslice),
    .vld_in(stream_out_32_TVALID_int_regslice),
    .ack_in(stream_out_32_TREADY_int_regslice),
    .data_out(stream_out_32_TDATA),
    .vld_out(regslice_both_stream_out_32_V_data_V_U_vld_out),
    .ack_out(stream_out_32_TREADY),
    .apdone_blk(regslice_both_stream_out_32_V_data_V_U_apdone_blk)
);

pixel_pack_regslice_both #(
    .DataWidth( 4 ))
regslice_both_stream_out_32_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd0),
    .vld_in(stream_out_32_TVALID_int_regslice),
    .ack_in(regslice_both_stream_out_32_V_keep_V_U_ack_in_dummy),
    .data_out(stream_out_32_TKEEP),
    .vld_out(regslice_both_stream_out_32_V_keep_V_U_vld_out),
    .ack_out(stream_out_32_TREADY),
    .apdone_blk(regslice_both_stream_out_32_V_keep_V_U_apdone_blk)
);

pixel_pack_regslice_both #(
    .DataWidth( 4 ))
regslice_both_stream_out_32_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd0),
    .vld_in(stream_out_32_TVALID_int_regslice),
    .ack_in(regslice_both_stream_out_32_V_strb_V_U_ack_in_dummy),
    .data_out(stream_out_32_TSTRB),
    .vld_out(regslice_both_stream_out_32_V_strb_V_U_vld_out),
    .ack_out(stream_out_32_TREADY),
    .apdone_blk(regslice_both_stream_out_32_V_strb_V_U_apdone_blk)
);

pixel_pack_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_out_32_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_out_32_TUSER_int_regslice),
    .vld_in(stream_out_32_TVALID_int_regslice),
    .ack_in(regslice_both_stream_out_32_V_user_V_U_ack_in_dummy),
    .data_out(stream_out_32_TUSER),
    .vld_out(regslice_both_stream_out_32_V_user_V_U_vld_out),
    .ack_out(stream_out_32_TREADY),
    .apdone_blk(regslice_both_stream_out_32_V_user_V_U_apdone_blk)
);

pixel_pack_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_out_32_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_out_32_TLAST_int_regslice),
    .vld_in(stream_out_32_TVALID_int_regslice),
    .ack_in(regslice_both_stream_out_32_V_last_V_U_ack_in_dummy),
    .data_out(stream_out_32_TLAST),
    .vld_out(regslice_both_stream_out_32_V_last_V_U_vld_out),
    .ack_out(stream_out_32_TREADY),
    .apdone_blk(regslice_both_stream_out_32_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp0_flush_enable)) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((grp_read_fu_156_p2 == 32'd4) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((((ap_enable_reg_pp0_iter0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone)) | ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone)))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((grp_read_fu_156_p2 == 32'd4) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp1_flush_enable)) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if (((grp_read_fu_156_p2 == 32'd3) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if ((((ap_enable_reg_pp1_iter0 == 1'b0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_subdone)) | ((1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_subdone)))) begin
            ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
        end else if (((grp_read_fu_156_p2 == 32'd3) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp1_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp2_exit_iter0_state10) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_subdone))) begin
            ap_enable_reg_pp2_iter0 <= 1'b0;
        end else if (((grp_read_fu_156_p2 == 32'd2) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp2_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter1 <= 1'b0;
    end else begin
        if ((((1'b1 == ap_CS_fsm_pp2_stage3) & (1'b0 == ap_block_pp2_stage3_subdone)) | ((1'b1 == ap_CS_fsm_pp2_stage0) & (ap_enable_reg_pp2_iter0 == 1'b0) & (1'b0 == ap_block_pp2_stage0_subdone)))) begin
            ap_enable_reg_pp2_iter1 <= ap_enable_reg_pp2_iter0;
        end else if (((grp_read_fu_156_p2 == 32'd2) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp2_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp3_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp3_flush_enable)) begin
            ap_enable_reg_pp3_iter0 <= 1'b0;
        end else if (((grp_read_fu_156_p2 == 32'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp3_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp3_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            ap_enable_reg_pp3_iter1 <= ap_enable_reg_pp3_iter0;
        end else if (((grp_read_fu_156_p2 == 32'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp3_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp4_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp4_stage0) & (1'b1 == ap_condition_pp4_exit_iter0_state19) & (1'b0 == ap_block_pp4_stage0_subdone))) begin
            ap_enable_reg_pp4_iter0 <= 1'b0;
        end else if (((grp_read_fu_156_p2 == 32'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp4_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp4_iter1 <= 1'b0;
    end else begin
        if ((((ap_enable_reg_pp4_iter0 == 1'b0) & (1'b1 == ap_CS_fsm_pp4_stage2) & (1'b0 == ap_block_pp4_stage2_subdone)) | ((1'b1 == ap_CS_fsm_pp4_stage3) & (1'b0 == ap_block_pp4_stage3_subdone)))) begin
            ap_enable_reg_pp4_iter1 <= ap_enable_reg_pp4_iter0;
        end else if (((grp_read_fu_156_p2 == 32'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp4_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1536)) begin
        if ((ap_phi_mux_last_4_phi_fu_226_p4 == 1'd1)) begin
            ap_phi_reg_pp2_iter0_data_V_8_0_reg_245 <= data_V_8_3_reg_332;
        end else if ((ap_phi_mux_last_4_phi_fu_226_p4 == 1'd0)) begin
            ap_phi_reg_pp2_iter0_data_V_8_0_reg_245 <= p_Result_11_fu_767_p5;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1540)) begin
        if ((last_6_0_reg_234 == 1'd1)) begin
            ap_phi_reg_pp2_iter0_data_V_8_1_reg_279 <= ap_phi_reg_pp2_iter0_data_V_8_0_reg_245;
        end else if ((last_6_0_reg_234 == 1'd0)) begin
            ap_phi_reg_pp2_iter0_data_V_8_1_reg_279 <= p_Result_34_1_fu_793_p5;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1545)) begin
        if ((last_6_1_reg_268 == 1'd1)) begin
            ap_phi_reg_pp2_iter0_data_V_8_2_reg_312 <= ap_phi_reg_pp2_iter0_data_V_8_1_reg_279;
        end else if ((last_6_1_reg_268 == 1'd0)) begin
            ap_phi_reg_pp2_iter0_data_V_8_2_reg_312 <= p_Result_34_2_fu_819_p5;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1536)) begin
        if ((ap_phi_mux_last_4_phi_fu_226_p4 == 1'd1)) begin
            ap_phi_reg_pp2_iter0_user_6_0_reg_256 <= 1'd0;
        end else if ((ap_phi_mux_last_4_phi_fu_226_p4 == 1'd0)) begin
            ap_phi_reg_pp2_iter0_user_6_0_reg_256 <= stream_in_24_TUSER_int_regslice;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1540)) begin
        if ((last_6_0_reg_234 == 1'd1)) begin
            ap_phi_reg_pp2_iter0_user_6_1_reg_290 <= ap_phi_reg_pp2_iter0_user_6_0_reg_256;
        end else if ((last_6_0_reg_234 == 1'd0)) begin
            ap_phi_reg_pp2_iter0_user_6_1_reg_290 <= or_ln70_fu_783_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1545)) begin
        if ((last_6_1_reg_268 == 1'd1)) begin
            ap_phi_reg_pp2_iter0_user_6_2_reg_322 <= ap_phi_reg_pp2_iter0_user_6_1_reg_290;
        end else if ((last_6_1_reg_268 == 1'd0)) begin
            ap_phi_reg_pp2_iter0_user_6_2_reg_322 <= or_ln70_1_fu_809_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1549)) begin
        if ((ap_phi_mux_last_phi_fu_426_p4 == 1'd1)) begin
            ap_phi_reg_pp4_iter0_buffer_V_3_0_reg_467 <= buffer_V_3_3_reg_587;
        end else if ((ap_phi_mux_last_phi_fu_426_p4 == 1'd0)) begin
            ap_phi_reg_pp4_iter0_buffer_V_3_0_reg_467 <= p_Result_s_fu_867_p5;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1553)) begin
        if ((last_2_0_reg_434 == 1'd1)) begin
            ap_phi_reg_pp4_iter0_buffer_V_3_1_reg_511 <= ap_phi_reg_pp4_iter0_buffer_V_3_0_reg_467;
        end else if ((last_2_0_reg_434 == 1'd0)) begin
            ap_phi_reg_pp4_iter0_buffer_V_3_1_reg_511 <= p_Result_1_fu_899_p5;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1558)) begin
        if ((last_2_1_reg_478 == 1'd1)) begin
            ap_phi_reg_pp4_iter0_buffer_V_3_2_reg_553 <= ap_phi_reg_pp4_iter0_buffer_V_3_1_reg_511;
        end else if ((last_2_1_reg_478 == 1'd0)) begin
            ap_phi_reg_pp4_iter0_buffer_V_3_2_reg_553 <= p_Result_2_fu_931_p5;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1549)) begin
        if ((ap_phi_mux_last_phi_fu_426_p4 == 1'd1)) begin
            ap_phi_reg_pp4_iter0_has_last_V_3_0_reg_456 <= has_last_V_3_3_reg_575;
        end else if ((ap_phi_mux_last_phi_fu_426_p4 == 1'd0)) begin
            ap_phi_reg_pp4_iter0_has_last_V_3_0_reg_456 <= tmp_1_fu_889_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1553)) begin
        if ((last_2_0_reg_434 == 1'd1)) begin
            ap_phi_reg_pp4_iter0_has_last_V_3_1_reg_500 <= ap_phi_reg_pp4_iter0_has_last_V_3_0_reg_456;
        end else if ((last_2_0_reg_434 == 1'd0)) begin
            ap_phi_reg_pp4_iter0_has_last_V_3_1_reg_500 <= tmp_3_fu_921_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1558)) begin
        if ((last_2_1_reg_478 == 1'd1)) begin
            ap_phi_reg_pp4_iter0_has_last_V_3_2_reg_543 <= ap_phi_reg_pp4_iter0_has_last_V_3_1_reg_500;
        end else if ((last_2_1_reg_478 == 1'd0)) begin
            ap_phi_reg_pp4_iter0_has_last_V_3_2_reg_543 <= tmp_5_fu_953_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1549)) begin
        if ((ap_phi_mux_last_phi_fu_426_p4 == 1'd1)) begin
            ap_phi_reg_pp4_iter0_has_user_V_3_0_reg_445 <= has_user_V_3_3_reg_563;
        end else if ((ap_phi_mux_last_phi_fu_426_p4 == 1'd0)) begin
            ap_phi_reg_pp4_iter0_has_user_V_3_0_reg_445 <= tmp_fu_879_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1553)) begin
        if ((last_2_0_reg_434 == 1'd1)) begin
            ap_phi_reg_pp4_iter0_has_user_V_3_1_reg_489 <= ap_phi_reg_pp4_iter0_has_user_V_3_0_reg_445;
        end else if ((last_2_0_reg_434 == 1'd0)) begin
            ap_phi_reg_pp4_iter0_has_user_V_3_1_reg_489 <= tmp_2_fu_911_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1558)) begin
        if ((last_2_1_reg_478 == 1'd1)) begin
            ap_phi_reg_pp4_iter0_has_user_V_3_2_reg_533 <= ap_phi_reg_pp4_iter0_has_user_V_3_1_reg_489;
        end else if ((last_2_1_reg_478 == 1'd0)) begin
            ap_phi_reg_pp4_iter0_has_user_V_3_2_reg_533 <= tmp_4_fu_943_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_876)) begin
        if (((last_2_2_reg_522 == 1'd1) & (delayed_last_reg_409 == 1'd0))) begin
            buffer_V_3_3_reg_587 <= ap_phi_reg_pp4_iter0_buffer_V_3_2_reg_553;
        end else if (((last_2_2_reg_522 == 1'd0) & (delayed_last_reg_409 == 1'd0))) begin
            buffer_V_3_3_reg_587 <= p_Result_3_fu_963_p5;
        end else if ((1'b1 == 1'b1)) begin
            buffer_V_3_3_reg_587 <= ap_phi_reg_pp4_iter0_buffer_V_3_3_reg_587;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_820)) begin
        if (((last_6_2_reg_301 == 1'd1) & (delayed_last_1_reg_209 == 1'd0))) begin
            data_V_8_3_reg_332 <= ap_phi_reg_pp2_iter0_data_V_8_2_reg_312;
        end else if (((last_6_2_reg_301 == 1'd0) & (delayed_last_1_reg_209 == 1'd0))) begin
            data_V_8_3_reg_332 <= p_Result_34_3_fu_846_p5;
        end else if ((1'b1 == 1'b1)) begin
            data_V_8_3_reg_332 <= ap_phi_reg_pp2_iter0_data_V_8_3_reg_332;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp2_iter1 == 1'b1) & (delayed_last_1_reg_209 == 1'd0) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        delayed_last_1_reg_209 <= last_4_reg_221;
    end else if (((grp_read_fu_156_p2 == 32'd2) & (1'b1 == ap_CS_fsm_state2))) begin
        delayed_last_1_reg_209 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp4_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0) & (delayed_last_reg_409 == 1'd0) & (1'b0 == ap_block_pp4_stage0_11001))) begin
        delayed_last_reg_409 <= last_reg_421;
    end else if (((grp_read_fu_156_p2 == 32'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        delayed_last_reg_409 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_876)) begin
        if (((last_2_2_reg_522 == 1'd1) & (delayed_last_reg_409 == 1'd0))) begin
            has_last_V_3_3_reg_575 <= ap_phi_reg_pp4_iter0_has_last_V_3_2_reg_543;
        end else if (((last_2_2_reg_522 == 1'd0) & (delayed_last_reg_409 == 1'd0))) begin
            has_last_V_3_3_reg_575 <= tmp_7_fu_987_p4;
        end else if ((1'b1 == 1'b1)) begin
            has_last_V_3_3_reg_575 <= ap_phi_reg_pp4_iter0_has_last_V_3_3_reg_575;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_876)) begin
        if (((last_2_2_reg_522 == 1'd1) & (delayed_last_reg_409 == 1'd0))) begin
            has_user_V_3_3_reg_563 <= ap_phi_reg_pp4_iter0_has_user_V_3_2_reg_533;
        end else if (((last_2_2_reg_522 == 1'd0) & (delayed_last_reg_409 == 1'd0))) begin
            has_user_V_3_3_reg_563 <= tmp_6_fu_976_p4;
        end else if ((1'b1 == 1'b1)) begin
            has_user_V_3_3_reg_563 <= ap_phi_reg_pp4_iter0_has_user_V_3_3_reg_563;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_843)) begin
        if (((ap_phi_mux_last_phi_fu_426_p4 == 1'd1) & (ap_phi_mux_delayed_last_phi_fu_413_p4 == 1'd0))) begin
            last_2_0_reg_434 <= 1'd1;
        end else if (((ap_phi_mux_last_phi_fu_426_p4 == 1'd0) & (ap_phi_mux_delayed_last_phi_fu_413_p4 == 1'd0))) begin
            last_2_0_reg_434 <= stream_in_24_TLAST_int_regslice;
        end else if ((1'b1 == 1'b1)) begin
            last_2_0_reg_434 <= ap_phi_reg_pp4_iter0_last_2_0_reg_434;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_850)) begin
        if (((last_2_0_reg_434 == 1'd1) & (delayed_last_reg_409 == 1'd0))) begin
            last_2_1_reg_478 <= 1'd1;
        end else if (((last_2_0_reg_434 == 1'd0) & (delayed_last_reg_409 == 1'd0))) begin
            last_2_1_reg_478 <= stream_in_24_TLAST_int_regslice;
        end else if ((1'b1 == 1'b1)) begin
            last_2_1_reg_478 <= ap_phi_reg_pp4_iter0_last_2_1_reg_478;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_863)) begin
        if (((last_2_1_reg_478 == 1'd1) & (delayed_last_reg_409 == 1'd0))) begin
            last_2_2_reg_522 <= 1'd1;
        end else if (((last_2_1_reg_478 == 1'd0) & (delayed_last_reg_409 == 1'd0))) begin
            last_2_2_reg_522 <= stream_in_24_TLAST_int_regslice;
        end else if ((1'b1 == 1'b1)) begin
            last_2_2_reg_522 <= ap_phi_reg_pp4_iter0_last_2_2_reg_522;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_876)) begin
        if (((last_2_2_reg_522 == 1'd1) & (delayed_last_reg_409 == 1'd0))) begin
            last_2_3_reg_599 <= 1'd1;
        end else if (((last_2_2_reg_522 == 1'd0) & (delayed_last_reg_409 == 1'd0))) begin
            last_2_3_reg_599 <= stream_in_24_TLAST_int_regslice;
        end else if ((1'b1 == 1'b1)) begin
            last_2_3_reg_599 <= ap_phi_reg_pp4_iter0_last_2_3_reg_599;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp2_iter1 == 1'b1) & (delayed_last_1_reg_209 == 1'd0) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        last_4_reg_221 <= last_6_3_reg_359;
    end else if (((grp_read_fu_156_p2 == 32'd2) & (1'b1 == ap_CS_fsm_state2))) begin
        last_4_reg_221 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_567)) begin
        if (((ap_phi_mux_last_4_phi_fu_226_p4 == 1'd1) & (ap_phi_mux_delayed_last_1_phi_fu_213_p4 == 1'd0))) begin
            last_6_0_reg_234 <= 1'd1;
        end else if (((ap_phi_mux_last_4_phi_fu_226_p4 == 1'd0) & (ap_phi_mux_delayed_last_1_phi_fu_213_p4 == 1'd0))) begin
            last_6_0_reg_234 <= stream_in_24_TLAST_int_regslice;
        end else if ((1'b1 == 1'b1)) begin
            last_6_0_reg_234 <= ap_phi_reg_pp2_iter0_last_6_0_reg_234;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_795)) begin
        if (((last_6_0_reg_234 == 1'd1) & (delayed_last_1_reg_209 == 1'd0))) begin
            last_6_1_reg_268 <= 1'd1;
        end else if (((last_6_0_reg_234 == 1'd0) & (delayed_last_1_reg_209 == 1'd0))) begin
            last_6_1_reg_268 <= stream_in_24_TLAST_int_regslice;
        end else if ((1'b1 == 1'b1)) begin
            last_6_1_reg_268 <= ap_phi_reg_pp2_iter0_last_6_1_reg_268;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_806)) begin
        if (((last_6_1_reg_268 == 1'd1) & (delayed_last_1_reg_209 == 1'd0))) begin
            last_6_2_reg_301 <= 1'd1;
        end else if (((last_6_1_reg_268 == 1'd0) & (delayed_last_1_reg_209 == 1'd0))) begin
            last_6_2_reg_301 <= stream_in_24_TLAST_int_regslice;
        end else if ((1'b1 == 1'b1)) begin
            last_6_2_reg_301 <= ap_phi_reg_pp2_iter0_last_6_2_reg_301;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_820)) begin
        if (((last_6_2_reg_301 == 1'd1) & (delayed_last_1_reg_209 == 1'd0))) begin
            last_6_3_reg_359 <= 1'd1;
        end else if (((last_6_2_reg_301 == 1'd0) & (delayed_last_1_reg_209 == 1'd0))) begin
            last_6_3_reg_359 <= stream_in_24_TLAST_int_regslice;
        end else if ((1'b1 == 1'b1)) begin
            last_6_3_reg_359 <= ap_phi_reg_pp2_iter0_last_6_3_reg_359;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp4_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0) & (delayed_last_reg_409 == 1'd0) & (1'b0 == ap_block_pp4_stage0_11001))) begin
        last_reg_421 <= last_2_3_reg_599;
    end else if (((grp_read_fu_156_p2 == 32'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        last_reg_421 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == alpha_0_ack_out) & (1'b1 == 1'b1) & (1'b1 == alpha_0_vld_reg)) | ((1'b0 == alpha_0_vld_reg) & (1'b1 == 1'b1)))) begin
        alpha_0_data_reg <= alpha;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        alpha_read_reg_1073 <= alpha_0_data_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        empty_36_reg_1117_3 <= stream_in_24_TUSER_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        empty_38_reg_1082_3 <= stream_in_24_TUSER_int_regslice;
        p_Result_5_reg_1092 <= {{stream_in_24_TDATA_int_regslice[23:16]}};
        p_Result_s_40_reg_1087 <= {{stream_in_24_TDATA_int_regslice[15:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp4_stage0) & (1'b0 == ap_block_pp4_stage0_11001))) begin
        last_reg_421_pp4_iter1_reg <= last_reg_421;
    end
end

always @ (posedge ap_clk) begin
    if ((((mode_0_ack_out == 1'b1) & (1'b1 == 1'b1) & (mode_0_vld_reg == 1'b1)) | ((1'b1 == 1'b1) & (mode_0_vld_reg == 1'b0)))) begin
        mode_0_data_reg <= mode;
    end
end

always @ (posedge ap_clk) begin
    if (((last_reg_421 == 1'd0) & (1'b1 == ap_CS_fsm_pp4_stage3) & (delayed_last_reg_409 == 1'd0) & (1'b0 == ap_block_pp4_stage3_11001))) begin
        p_Result_28_1_reg_1247 <= {{ap_phi_mux_buffer_V_3_3_phi_fu_591_p4[63:32]}};
        p_Result_28_2_reg_1262 <= {{ap_phi_mux_buffer_V_3_3_phi_fu_591_p4[95:64]}};
        p_Result_29_1_reg_1252 <= ap_phi_mux_has_user_V_3_3_phi_fu_567_p4[4'd1];
        p_Result_29_2_reg_1267 <= ap_phi_mux_has_user_V_3_3_phi_fu_567_p4[4'd2];
        p_Result_30_1_reg_1257 <= ap_phi_mux_has_last_V_3_3_phi_fu_579_p4[4'd2];
        p_Result_30_2_reg_1272 <= ap_phi_mux_has_last_V_3_3_phi_fu_579_p4[4'd3];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        trunc_ln215_reg_1122 <= trunc_ln215_fu_733_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        trunc_ln674_reg_1097 <= trunc_ln674_fu_653_p1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state6) & (regslice_both_stream_out_32_V_data_V_U_apdone_blk == 1'b0)))) begin
        alpha_0_ack_out = 1'b1;
    end else begin
        alpha_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if (((grp_fu_635_p1 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
        ap_condition_pp0_flush_enable = 1'b1;
    end else begin
        ap_condition_pp0_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if (((grp_fu_635_p1 == 1'd1) & (1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_subdone))) begin
        ap_condition_pp1_flush_enable = 1'b1;
    end else begin
        ap_condition_pp1_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if ((ap_phi_mux_delayed_last_1_phi_fu_213_p4 == 1'd1)) begin
        ap_condition_pp2_exit_iter0_state10 = 1'b1;
    end else begin
        ap_condition_pp2_exit_iter0_state10 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_fu_635_p1 == 1'd1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_subdone))) begin
        ap_condition_pp3_flush_enable = 1'b1;
    end else begin
        ap_condition_pp3_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if ((ap_phi_mux_delayed_last_phi_fu_413_p4 == 1'd1)) begin
        ap_condition_pp4_exit_iter0_state19 = 1'b1;
    end else begin
        ap_condition_pp4_exit_iter0_state19 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter1 == 1'b0) & (ap_enable_reg_pp2_iter0 == 1'b0))) begin
        ap_idle_pp2 = 1'b1;
    end else begin
        ap_idle_pp2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter1 == 1'b0) & (ap_enable_reg_pp3_iter0 == 1'b0))) begin
        ap_idle_pp3 = 1'b1;
    end else begin
        ap_idle_pp3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp4_iter0 == 1'b0) & (ap_enable_reg_pp4_iter1 == 1'b0))) begin
        ap_idle_pp4 = 1'b1;
    end else begin
        ap_idle_pp4 = 1'b0;
    end
end

always @ (*) begin
    if ((delayed_last_reg_409 == 1'd0)) begin
        if ((last_2_2_reg_522 == 1'd1)) begin
            ap_phi_mux_buffer_V_3_3_phi_fu_591_p4 = ap_phi_reg_pp4_iter0_buffer_V_3_2_reg_553;
        end else if ((last_2_2_reg_522 == 1'd0)) begin
            ap_phi_mux_buffer_V_3_3_phi_fu_591_p4 = p_Result_3_fu_963_p5;
        end else begin
            ap_phi_mux_buffer_V_3_3_phi_fu_591_p4 = ap_phi_reg_pp4_iter0_buffer_V_3_3_reg_587;
        end
    end else begin
        ap_phi_mux_buffer_V_3_3_phi_fu_591_p4 = ap_phi_reg_pp4_iter0_buffer_V_3_3_reg_587;
    end
end

always @ (*) begin
    if ((delayed_last_1_reg_209 == 1'd0)) begin
        if ((last_6_2_reg_301 == 1'd1)) begin
            ap_phi_mux_data_V_8_3_phi_fu_337_p4 = ap_phi_reg_pp2_iter0_data_V_8_2_reg_312;
        end else if ((last_6_2_reg_301 == 1'd0)) begin
            ap_phi_mux_data_V_8_3_phi_fu_337_p4 = p_Result_34_3_fu_846_p5;
        end else begin
            ap_phi_mux_data_V_8_3_phi_fu_337_p4 = ap_phi_reg_pp2_iter0_data_V_8_3_reg_332;
        end
    end else begin
        ap_phi_mux_data_V_8_3_phi_fu_337_p4 = ap_phi_reg_pp2_iter0_data_V_8_3_reg_332;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter1 == 1'b1) & (delayed_last_1_reg_209 == 1'd0) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0))) begin
        ap_phi_mux_delayed_last_1_phi_fu_213_p4 = last_4_reg_221;
    end else begin
        ap_phi_mux_delayed_last_1_phi_fu_213_p4 = delayed_last_1_reg_209;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp4_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0) & (delayed_last_reg_409 == 1'd0) & (1'b0 == ap_block_pp4_stage0))) begin
        ap_phi_mux_delayed_last_phi_fu_413_p4 = last_reg_421;
    end else begin
        ap_phi_mux_delayed_last_phi_fu_413_p4 = delayed_last_reg_409;
    end
end

always @ (*) begin
    if ((delayed_last_reg_409 == 1'd0)) begin
        if ((last_2_2_reg_522 == 1'd1)) begin
            ap_phi_mux_has_last_V_3_3_phi_fu_579_p4 = ap_phi_reg_pp4_iter0_has_last_V_3_2_reg_543;
        end else if ((last_2_2_reg_522 == 1'd0)) begin
            ap_phi_mux_has_last_V_3_3_phi_fu_579_p4 = tmp_7_fu_987_p4;
        end else begin
            ap_phi_mux_has_last_V_3_3_phi_fu_579_p4 = ap_phi_reg_pp4_iter0_has_last_V_3_3_reg_575;
        end
    end else begin
        ap_phi_mux_has_last_V_3_3_phi_fu_579_p4 = ap_phi_reg_pp4_iter0_has_last_V_3_3_reg_575;
    end
end

always @ (*) begin
    if ((delayed_last_reg_409 == 1'd0)) begin
        if ((last_2_2_reg_522 == 1'd1)) begin
            ap_phi_mux_has_user_V_3_3_phi_fu_567_p4 = ap_phi_reg_pp4_iter0_has_user_V_3_2_reg_533;
        end else if ((last_2_2_reg_522 == 1'd0)) begin
            ap_phi_mux_has_user_V_3_3_phi_fu_567_p4 = tmp_6_fu_976_p4;
        end else begin
            ap_phi_mux_has_user_V_3_3_phi_fu_567_p4 = ap_phi_reg_pp4_iter0_has_user_V_3_3_reg_563;
        end
    end else begin
        ap_phi_mux_has_user_V_3_3_phi_fu_567_p4 = ap_phi_reg_pp4_iter0_has_user_V_3_3_reg_563;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter1 == 1'b1) & (delayed_last_1_reg_209 == 1'd0) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0))) begin
        ap_phi_mux_last_4_phi_fu_226_p4 = last_6_3_reg_359;
    end else begin
        ap_phi_mux_last_4_phi_fu_226_p4 = last_4_reg_221;
    end
end

always @ (*) begin
    if ((delayed_last_1_reg_209 == 1'd0)) begin
        if ((last_6_2_reg_301 == 1'd1)) begin
            ap_phi_mux_last_6_3_phi_fu_364_p4 = 1'd1;
        end else if ((last_6_2_reg_301 == 1'd0)) begin
            ap_phi_mux_last_6_3_phi_fu_364_p4 = stream_in_24_TLAST_int_regslice;
        end else begin
            ap_phi_mux_last_6_3_phi_fu_364_p4 = ap_phi_reg_pp2_iter0_last_6_3_reg_359;
        end
    end else begin
        ap_phi_mux_last_6_3_phi_fu_364_p4 = ap_phi_reg_pp2_iter0_last_6_3_reg_359;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp4_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0) & (delayed_last_reg_409 == 1'd0) & (1'b0 == ap_block_pp4_stage0))) begin
        ap_phi_mux_last_phi_fu_426_p4 = last_2_3_reg_599;
    end else begin
        ap_phi_mux_last_phi_fu_426_p4 = last_reg_421;
    end
end

always @ (*) begin
    if ((delayed_last_1_reg_209 == 1'd0)) begin
        if ((last_6_2_reg_301 == 1'd1)) begin
            ap_phi_mux_user_6_3_phi_fu_350_p4 = ap_phi_reg_pp2_iter0_user_6_2_reg_322;
        end else if ((last_6_2_reg_301 == 1'd0)) begin
            ap_phi_mux_user_6_3_phi_fu_350_p4 = or_ln70_2_fu_835_p2;
        end else begin
            ap_phi_mux_user_6_3_phi_fu_350_p4 = ap_phi_reg_pp2_iter0_user_6_3_reg_346;
        end
    end else begin
        ap_phi_mux_user_6_3_phi_fu_350_p4 = ap_phi_reg_pp2_iter0_user_6_3_reg_346;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state6) & (regslice_both_stream_out_32_V_data_V_U_apdone_blk == 1'b0)))) begin
        mode_0_ack_out = 1'b1;
    end else begin
        mode_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp4_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0) & (ap_phi_mux_last_phi_fu_426_p4 == 1'd0) & (ap_phi_mux_delayed_last_phi_fu_413_p4 == 1'd0) & (1'b0 == ap_block_pp4_stage0)) | ((ap_enable_reg_pp4_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage3) & (last_2_2_reg_522 == 1'd0) & (delayed_last_reg_409 == 1'd0) & (1'b0 == ap_block_pp4_stage3)) | ((ap_enable_reg_pp4_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage2) & (last_2_1_reg_478 == 1'd0) & (delayed_last_reg_409 == 1'd0) & (1'b0 == ap_block_pp4_stage2)) | ((ap_enable_reg_pp4_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage1) & (last_2_0_reg_434 == 1'd0) & (delayed_last_reg_409 == 1'd0) & (1'b0 == ap_block_pp4_stage1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1)) | ((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0)) | ((last_6_2_reg_301 == 1'd0) & (delayed_last_1_reg_209 == 1'd0) & (1'b1 == ap_CS_fsm_pp2_stage3) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage3)) | ((last_6_1_reg_268 == 1'd0) & (delayed_last_1_reg_209 == 1'd0) & (1'b1 == ap_CS_fsm_pp2_stage2) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage2)) | ((last_6_0_reg_234 == 1'd0) & (delayed_last_1_reg_209 == 1'd0) & (1'b1 == ap_CS_fsm_pp2_stage1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage1)) | ((1'b1 == ap_CS_fsm_pp2_stage0) & (ap_phi_mux_last_4_phi_fu_226_p4 == 1'd0) & (ap_phi_mux_delayed_last_1_phi_fu_213_p4 == 1'd0) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage0)) | ((1'b1 == ap_CS_fsm_pp3_stage0) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b0 == ap_block_pp3_stage0)))) begin
        stream_in_24_TDATA_blk_n = stream_in_24_TVALID_int_regslice;
    end else begin
        stream_in_24_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp4_iter0 == 1'b1) & (ap_predicate_op223_read_state22 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage3) & (1'b0 == ap_block_pp4_stage3_11001)) | ((ap_enable_reg_pp4_iter0 == 1'b1) & (ap_predicate_op210_read_state21 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage2) & (1'b0 == ap_block_pp4_stage2_11001)) | ((ap_enable_reg_pp4_iter0 == 1'b1) & (ap_predicate_op197_read_state20 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage1) & (1'b0 == ap_block_pp4_stage1_11001)) | ((ap_enable_reg_pp4_iter0 == 1'b1) & (ap_predicate_op183_read_state19 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0) & (1'b0 == ap_block_pp4_stage0_11001)) | ((ap_predicate_op147_read_state13 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage3) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage3_11001)) | ((ap_predicate_op135_read_state12 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage2) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage2_11001)) | ((ap_predicate_op123_read_state11 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage1_11001)) | ((ap_predicate_op111_read_state10 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_11001)) | ((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)) | ((1'b1 == ap_CS_fsm_pp3_stage0) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)))) begin
        stream_in_24_TREADY_int_regslice = 1'b1;
    end else begin
        stream_in_24_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp4_iter0 == 1'b1) & (last_reg_421 == 1'd0) & (1'b1 == ap_CS_fsm_pp4_stage3) & (delayed_last_reg_409 == 1'd0) & (1'b0 == ap_block_pp4_stage3)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0)) | ((ap_enable_reg_pp2_iter1 == 1'b1) & (last_4_reg_221 == 1'd0) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0)) | ((last_4_reg_221 == 1'd0) & (delayed_last_1_reg_209 == 1'd0) & (1'b1 == ap_CS_fsm_pp2_stage3) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage3)) | ((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0)) | ((last_reg_421_pp4_iter1_reg == 1'd0) & (ap_enable_reg_pp4_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage2) & (1'b0 == ap_block_pp4_stage2)) | ((last_reg_421_pp4_iter1_reg == 1'd0) & (ap_enable_reg_pp4_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage1) & (1'b0 == ap_block_pp4_stage1)) | ((ap_enable_reg_pp4_iter1 == 1'b1) & (last_reg_421 == 1'd0) & (1'b1 == ap_CS_fsm_pp4_stage0) & (1'b0 == ap_block_pp4_stage0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1)) | ((1'b1 == ap_CS_fsm_pp3_stage0) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b0 == ap_block_pp3_stage0)))) begin
        stream_out_32_TDATA_blk_n = stream_out_32_TREADY_int_regslice;
    end else begin
        stream_out_32_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((last_reg_421_pp4_iter1_reg == 1'd0) & (ap_enable_reg_pp4_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage1) & (1'b0 == ap_block_pp4_stage1_01001))) begin
        stream_out_32_TDATA_int_regslice = p_Result_28_2_reg_1262;
    end else if (((ap_enable_reg_pp4_iter1 == 1'b1) & (last_reg_421 == 1'd0) & (1'b1 == ap_CS_fsm_pp4_stage0) & (1'b0 == ap_block_pp4_stage0_01001))) begin
        stream_out_32_TDATA_int_regslice = p_Result_28_1_reg_1247;
    end else if (((ap_enable_reg_pp4_iter0 == 1'b1) & (ap_predicate_op239_write_state22 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage3) & (1'b0 == ap_block_pp4_stage3_01001))) begin
        stream_out_32_TDATA_int_regslice = trunc_ln674_6_fu_998_p1;
    end else if (((1'b1 == ap_CS_fsm_pp3_stage0) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b0 == ap_block_pp3_stage0_01001))) begin
        stream_out_32_TDATA_int_regslice = p_Result_14_fu_859_p3;
    end else if (((ap_predicate_op159_write_state13 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage3) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage3_01001))) begin
        stream_out_32_TDATA_int_regslice = ap_phi_mux_data_V_8_3_phi_fu_337_p4;
    end else if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_01001))) begin
        stream_out_32_TDATA_int_regslice = p_Result_36_1_fu_755_p3;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_01001))) begin
        stream_out_32_TDATA_int_regslice = p_Result_15_fu_721_p5;
    end else begin
        stream_out_32_TDATA_int_regslice = 'bx;
    end
end

always @ (*) begin
    if (((last_reg_421_pp4_iter1_reg == 1'd0) & (ap_enable_reg_pp4_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage1) & (1'b0 == ap_block_pp4_stage1_01001))) begin
        stream_out_32_TLAST_int_regslice = p_Result_30_2_reg_1272;
    end else if (((ap_enable_reg_pp4_iter1 == 1'b1) & (last_reg_421 == 1'd0) & (1'b1 == ap_CS_fsm_pp4_stage0) & (1'b0 == ap_block_pp4_stage0_01001))) begin
        stream_out_32_TLAST_int_regslice = p_Result_30_1_reg_1257;
    end else if (((ap_enable_reg_pp4_iter0 == 1'b1) & (ap_predicate_op239_write_state22 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage3) & (1'b0 == ap_block_pp4_stage3_01001))) begin
        stream_out_32_TLAST_int_regslice = ap_phi_mux_has_last_V_3_3_phi_fu_579_p4[4'd1];
    end else if (((ap_predicate_op159_write_state13 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage3) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage3_01001))) begin
        stream_out_32_TLAST_int_regslice = ap_phi_mux_last_6_3_phi_fu_364_p4;
    end else if ((((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_01001)) | ((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_01001)) | ((1'b1 == ap_CS_fsm_pp3_stage0) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b0 == ap_block_pp3_stage0_01001)))) begin
        stream_out_32_TLAST_int_regslice = stream_in_24_TLAST_int_regslice;
    end else begin
        stream_out_32_TLAST_int_regslice = 'bx;
    end
end

always @ (*) begin
    if (((last_reg_421_pp4_iter1_reg == 1'd0) & (ap_enable_reg_pp4_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage1) & (1'b0 == ap_block_pp4_stage1_01001))) begin
        stream_out_32_TUSER_int_regslice = p_Result_29_2_reg_1267;
    end else if (((ap_enable_reg_pp4_iter1 == 1'b1) & (last_reg_421 == 1'd0) & (1'b1 == ap_CS_fsm_pp4_stage0) & (1'b0 == ap_block_pp4_stage0_01001))) begin
        stream_out_32_TUSER_int_regslice = p_Result_29_1_reg_1252;
    end else if (((ap_enable_reg_pp4_iter0 == 1'b1) & (ap_predicate_op239_write_state22 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage3) & (1'b0 == ap_block_pp4_stage3_01001))) begin
        stream_out_32_TUSER_int_regslice = ap_phi_mux_has_user_V_3_3_phi_fu_567_p4[4'd0];
    end else if (((1'b1 == ap_CS_fsm_pp3_stage0) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b0 == ap_block_pp3_stage0_01001))) begin
        stream_out_32_TUSER_int_regslice = stream_in_24_TUSER_int_regslice;
    end else if (((ap_predicate_op159_write_state13 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage3) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage3_01001))) begin
        stream_out_32_TUSER_int_regslice = ap_phi_mux_user_6_3_phi_fu_350_p4;
    end else if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_01001))) begin
        stream_out_32_TUSER_int_regslice = or_ln90_fu_744_p2;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_01001))) begin
        stream_out_32_TUSER_int_regslice = or_ln107_fu_664_p2;
    end else begin
        stream_out_32_TUSER_int_regslice = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp4_iter0 == 1'b1) & (ap_predicate_op239_write_state22 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage3) & (1'b0 == ap_block_pp4_stage3_11001)) | ((ap_predicate_op159_write_state13 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage3) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage3_11001)) | ((last_reg_421_pp4_iter1_reg == 1'd0) & (ap_enable_reg_pp4_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage1) & (1'b0 == ap_block_pp4_stage1_11001)) | ((ap_enable_reg_pp4_iter1 == 1'b1) & (last_reg_421 == 1'd0) & (1'b1 == ap_CS_fsm_pp4_stage0) & (1'b0 == ap_block_pp4_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp3_stage0) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)))) begin
        stream_out_32_TVALID_int_regslice = 1'b1;
    end else begin
        stream_out_32_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            if (((grp_read_fu_156_p2 == 32'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_pp4_stage0;
            end else if (((grp_read_fu_156_p2 == 32'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage0;
            end else if (((grp_read_fu_156_p2 == 32'd2) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else if (((grp_read_fu_156_p2 == 32'd3) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if (((grp_read_fu_156_p2 == 32'd4) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (regslice_both_stream_out_32_V_data_V_U_apdone_blk == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_pp1_stage0 : begin
            if ((~((ap_enable_reg_pp1_iter1 == 1'b1) & (ap_enable_reg_pp1_iter0 == 1'b0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_subdone)) & (1'b0 == ap_block_pp1_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage1;
            end else if (((ap_enable_reg_pp1_iter1 == 1'b1) & (ap_enable_reg_pp1_iter0 == 1'b0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_pp1_stage1 : begin
            if ((1'b0 == ap_block_pp1_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage1;
            end
        end
        ap_ST_fsm_pp2_stage0 : begin
            if ((~((ap_phi_mux_delayed_last_1_phi_fu_213_p4 == 1'd1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage0_subdone)) & (1'b0 == ap_block_pp2_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage1;
            end else if (((ap_phi_mux_delayed_last_1_phi_fu_213_p4 == 1'd1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end
        end
        ap_ST_fsm_pp2_stage1 : begin
            if ((1'b0 == ap_block_pp2_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage1;
            end
        end
        ap_ST_fsm_pp2_stage2 : begin
            if ((1'b0 == ap_block_pp2_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage2;
            end
        end
        ap_ST_fsm_pp2_stage3 : begin
            if ((1'b0 == ap_block_pp2_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage3;
            end
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_pp3_stage0 : begin
            if (~((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (ap_enable_reg_pp3_iter0 == 1'b0) & (1'b0 == ap_block_pp3_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage0;
            end else if (((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (ap_enable_reg_pp3_iter0 == 1'b0) & (1'b0 == ap_block_pp3_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage0;
            end
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_pp4_stage0 : begin
            if ((~((ap_enable_reg_pp4_iter0 == 1'b1) & (ap_enable_reg_pp4_iter1 == 1'b0) & (ap_phi_mux_delayed_last_phi_fu_413_p4 == 1'd1) & (1'b0 == ap_block_pp4_stage0_subdone)) & (1'b0 == ap_block_pp4_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp4_stage1;
            end else if (((ap_enable_reg_pp4_iter0 == 1'b1) & (ap_enable_reg_pp4_iter1 == 1'b0) & (ap_phi_mux_delayed_last_phi_fu_413_p4 == 1'd1) & (1'b0 == ap_block_pp4_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp4_stage0;
            end
        end
        ap_ST_fsm_pp4_stage1 : begin
            if ((1'b0 == ap_block_pp4_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp4_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp4_stage1;
            end
        end
        ap_ST_fsm_pp4_stage2 : begin
            if ((~((ap_enable_reg_pp4_iter0 == 1'b0) & (ap_enable_reg_pp4_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage2) & (1'b0 == ap_block_pp4_stage2_subdone)) & (1'b0 == ap_block_pp4_stage2_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp4_stage3;
            end else if (((ap_enable_reg_pp4_iter0 == 1'b0) & (ap_enable_reg_pp4_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage2) & (1'b0 == ap_block_pp4_stage2_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp4_stage2;
            end
        end
        ap_ST_fsm_pp4_stage3 : begin
            if ((1'b0 == ap_block_pp4_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp4_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp4_stage3;
            end
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp1_stage1 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp2_stage0 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_pp2_stage1 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_pp2_stage2 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_pp2_stage3 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_pp3_stage0 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_pp4_stage0 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_pp4_stage1 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_pp4_stage2 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_pp4_stage3 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (stream_out_32_TREADY_int_regslice == 1'b0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (stream_in_24_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (stream_out_32_TREADY_int_regslice == 1'b0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (stream_in_24_TVALID_int_regslice == 1'b0)));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_01001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((stream_out_32_TREADY_int_regslice == 1'b0) | (stream_in_24_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((stream_out_32_TREADY_int_regslice == 1'b0) | (stream_in_24_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((stream_out_32_TREADY_int_regslice == 1'b0) | (stream_in_24_TVALID_int_regslice == 1'b0)));
end

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp1_stage0_11001 = (((ap_enable_reg_pp1_iter1 == 1'b1) & (stream_out_32_TREADY_int_regslice == 1'b0)) | ((ap_enable_reg_pp1_iter0 == 1'b1) & (stream_in_24_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_pp1_stage0_subdone = (((ap_enable_reg_pp1_iter1 == 1'b1) & (stream_out_32_TREADY_int_regslice == 1'b0)) | ((ap_enable_reg_pp1_iter0 == 1'b1) & (stream_in_24_TVALID_int_regslice == 1'b0)));
end

assign ap_block_pp1_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp1_stage1_01001 = ((ap_enable_reg_pp1_iter0 == 1'b1) & ((stream_out_32_TREADY_int_regslice == 1'b0) | (stream_in_24_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_pp1_stage1_11001 = ((ap_enable_reg_pp1_iter0 == 1'b1) & ((stream_out_32_TREADY_int_regslice == 1'b0) | (stream_in_24_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_pp1_stage1_subdone = ((ap_enable_reg_pp1_iter0 == 1'b1) & ((stream_out_32_TREADY_int_regslice == 1'b0) | (stream_in_24_TVALID_int_regslice == 1'b0)));
end

assign ap_block_pp2_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp2_stage0_11001 = (((ap_predicate_op111_read_state10 == 1'b1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (stream_in_24_TVALID_int_regslice == 1'b0)) | ((ap_enable_reg_pp2_iter1 == 1'b1) & ((1'b1 == ap_block_state14_io) | ((last_4_reg_221 == 1'd0) & (stream_out_32_TREADY_int_regslice == 1'b0)))));
end

always @ (*) begin
    ap_block_pp2_stage0_subdone = (((ap_predicate_op111_read_state10 == 1'b1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (stream_in_24_TVALID_int_regslice == 1'b0)) | ((ap_enable_reg_pp2_iter1 == 1'b1) & ((1'b1 == ap_block_state14_io) | ((last_4_reg_221 == 1'd0) & (stream_out_32_TREADY_int_regslice == 1'b0)))));
end

assign ap_block_pp2_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp2_stage1_11001 = ((ap_predicate_op123_read_state11 == 1'b1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (stream_in_24_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_pp2_stage1_subdone = ((ap_predicate_op123_read_state11 == 1'b1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (stream_in_24_TVALID_int_regslice == 1'b0));
end

assign ap_block_pp2_stage2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp2_stage2_11001 = ((ap_predicate_op135_read_state12 == 1'b1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (stream_in_24_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_pp2_stage2_subdone = ((ap_predicate_op135_read_state12 == 1'b1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (stream_in_24_TVALID_int_regslice == 1'b0));
end

assign ap_block_pp2_stage3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp2_stage3_01001 = ((ap_enable_reg_pp2_iter0 == 1'b1) & (((ap_predicate_op159_write_state13 == 1'b1) & (stream_out_32_TREADY_int_regslice == 1'b0)) | ((ap_predicate_op147_read_state13 == 1'b1) & (stream_in_24_TVALID_int_regslice == 1'b0))));
end

always @ (*) begin
    ap_block_pp2_stage3_11001 = ((ap_enable_reg_pp2_iter0 == 1'b1) & ((1'b1 == ap_block_state13_io) | ((ap_predicate_op159_write_state13 == 1'b1) & (stream_out_32_TREADY_int_regslice == 1'b0)) | ((ap_predicate_op147_read_state13 == 1'b1) & (stream_in_24_TVALID_int_regslice == 1'b0))));
end

always @ (*) begin
    ap_block_pp2_stage3_subdone = ((ap_enable_reg_pp2_iter0 == 1'b1) & ((1'b1 == ap_block_state13_io) | ((ap_predicate_op159_write_state13 == 1'b1) & (stream_out_32_TREADY_int_regslice == 1'b0)) | ((ap_predicate_op147_read_state13 == 1'b1) & (stream_in_24_TVALID_int_regslice == 1'b0))));
end

assign ap_block_pp3_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp3_stage0_01001 = (((ap_enable_reg_pp3_iter1 == 1'b1) & (stream_out_32_TREADY_int_regslice == 1'b0)) | ((ap_enable_reg_pp3_iter0 == 1'b1) & ((stream_out_32_TREADY_int_regslice == 1'b0) | (stream_in_24_TVALID_int_regslice == 1'b0))));
end

always @ (*) begin
    ap_block_pp3_stage0_11001 = (((ap_enable_reg_pp3_iter1 == 1'b1) & (stream_out_32_TREADY_int_regslice == 1'b0)) | ((ap_enable_reg_pp3_iter0 == 1'b1) & ((stream_out_32_TREADY_int_regslice == 1'b0) | (stream_in_24_TVALID_int_regslice == 1'b0))));
end

always @ (*) begin
    ap_block_pp3_stage0_subdone = (((ap_enable_reg_pp3_iter1 == 1'b1) & (stream_out_32_TREADY_int_regslice == 1'b0)) | ((ap_enable_reg_pp3_iter0 == 1'b1) & ((stream_out_32_TREADY_int_regslice == 1'b0) | (stream_in_24_TVALID_int_regslice == 1'b0))));
end

assign ap_block_pp4_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp4_stage0_01001 = (((ap_enable_reg_pp4_iter0 == 1'b1) & (ap_predicate_op183_read_state19 == 1'b1) & (stream_in_24_TVALID_int_regslice == 1'b0)) | ((ap_enable_reg_pp4_iter1 == 1'b1) & (last_reg_421 == 1'd0) & (stream_out_32_TREADY_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_pp4_stage0_11001 = (((ap_enable_reg_pp4_iter0 == 1'b1) & (ap_predicate_op183_read_state19 == 1'b1) & (stream_in_24_TVALID_int_regslice == 1'b0)) | ((ap_enable_reg_pp4_iter1 == 1'b1) & ((1'b1 == ap_block_state23_io) | ((last_reg_421 == 1'd0) & (stream_out_32_TREADY_int_regslice == 1'b0)))));
end

always @ (*) begin
    ap_block_pp4_stage0_subdone = (((ap_enable_reg_pp4_iter0 == 1'b1) & (ap_predicate_op183_read_state19 == 1'b1) & (stream_in_24_TVALID_int_regslice == 1'b0)) | ((ap_enable_reg_pp4_iter1 == 1'b1) & ((1'b1 == ap_block_state23_io) | ((last_reg_421 == 1'd0) & (stream_out_32_TREADY_int_regslice == 1'b0)))));
end

assign ap_block_pp4_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp4_stage1_01001 = (((ap_enable_reg_pp4_iter0 == 1'b1) & (ap_predicate_op197_read_state20 == 1'b1) & (stream_in_24_TVALID_int_regslice == 1'b0)) | ((last_reg_421_pp4_iter1_reg == 1'd0) & (ap_enable_reg_pp4_iter1 == 1'b1) & (stream_out_32_TREADY_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_pp4_stage1_11001 = (((ap_enable_reg_pp4_iter0 == 1'b1) & (ap_predicate_op197_read_state20 == 1'b1) & (stream_in_24_TVALID_int_regslice == 1'b0)) | ((ap_enable_reg_pp4_iter1 == 1'b1) & ((1'b1 == ap_block_state24_io) | ((last_reg_421_pp4_iter1_reg == 1'd0) & (stream_out_32_TREADY_int_regslice == 1'b0)))));
end

always @ (*) begin
    ap_block_pp4_stage1_subdone = (((ap_enable_reg_pp4_iter0 == 1'b1) & (ap_predicate_op197_read_state20 == 1'b1) & (stream_in_24_TVALID_int_regslice == 1'b0)) | ((ap_enable_reg_pp4_iter1 == 1'b1) & ((1'b1 == ap_block_state24_io) | ((last_reg_421_pp4_iter1_reg == 1'd0) & (stream_out_32_TREADY_int_regslice == 1'b0)))));
end

assign ap_block_pp4_stage2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp4_stage2_11001 = (((ap_enable_reg_pp4_iter0 == 1'b1) & (ap_predicate_op210_read_state21 == 1'b1) & (stream_in_24_TVALID_int_regslice == 1'b0)) | ((ap_enable_reg_pp4_iter1 == 1'b1) & ((1'b1 == ap_block_state25_io) | ((last_reg_421_pp4_iter1_reg == 1'd0) & (stream_out_32_TREADY_int_regslice == 1'b0)))));
end

always @ (*) begin
    ap_block_pp4_stage2_subdone = (((ap_enable_reg_pp4_iter0 == 1'b1) & (ap_predicate_op210_read_state21 == 1'b1) & (stream_in_24_TVALID_int_regslice == 1'b0)) | ((ap_enable_reg_pp4_iter1 == 1'b1) & ((1'b1 == ap_block_state25_io) | ((last_reg_421_pp4_iter1_reg == 1'd0) & (stream_out_32_TREADY_int_regslice == 1'b0)))));
end

assign ap_block_pp4_stage3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp4_stage3_01001 = ((ap_enable_reg_pp4_iter0 == 1'b1) & (((ap_predicate_op239_write_state22 == 1'b1) & (stream_out_32_TREADY_int_regslice == 1'b0)) | ((ap_predicate_op223_read_state22 == 1'b1) & (stream_in_24_TVALID_int_regslice == 1'b0))));
end

always @ (*) begin
    ap_block_pp4_stage3_11001 = ((ap_enable_reg_pp4_iter0 == 1'b1) & ((1'b1 == ap_block_state22_io) | ((ap_predicate_op239_write_state22 == 1'b1) & (stream_out_32_TREADY_int_regslice == 1'b0)) | ((ap_predicate_op223_read_state22 == 1'b1) & (stream_in_24_TVALID_int_regslice == 1'b0))));
end

always @ (*) begin
    ap_block_pp4_stage3_subdone = ((ap_enable_reg_pp4_iter0 == 1'b1) & ((1'b1 == ap_block_state22_io) | ((ap_predicate_op239_write_state22 == 1'b1) & (stream_out_32_TREADY_int_regslice == 1'b0)) | ((ap_predicate_op223_read_state22 == 1'b1) & (stream_in_24_TVALID_int_regslice == 1'b0))));
end

always @ (*) begin
    ap_block_state10_pp2_stage0_iter0 = ((ap_predicate_op111_read_state10 == 1'b1) & (stream_in_24_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state11_pp2_stage1_iter0 = ((ap_predicate_op123_read_state11 == 1'b1) & (stream_in_24_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state12_pp2_stage2_iter0 = ((ap_predicate_op135_read_state12 == 1'b1) & (stream_in_24_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state13_io = ((ap_predicate_op159_write_state13 == 1'b1) & (stream_out_32_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state13_pp2_stage3_iter0 = (((ap_predicate_op159_write_state13 == 1'b1) & (stream_out_32_TREADY_int_regslice == 1'b0)) | ((ap_predicate_op147_read_state13 == 1'b1) & (stream_in_24_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_state14_io = ((last_4_reg_221 == 1'd0) & (stream_out_32_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state14_pp2_stage0_iter1 = ((last_4_reg_221 == 1'd0) & (stream_out_32_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state16_pp3_stage0_iter0 = ((stream_out_32_TREADY_int_regslice == 1'b0) | (stream_in_24_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state17_pp3_stage0_iter1 = (stream_out_32_TREADY_int_regslice == 1'b0);
end

always @ (*) begin
    ap_block_state19_pp4_stage0_iter0 = ((ap_predicate_op183_read_state19 == 1'b1) & (stream_in_24_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state20_pp4_stage1_iter0 = ((ap_predicate_op197_read_state20 == 1'b1) & (stream_in_24_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state21_pp4_stage2_iter0 = ((ap_predicate_op210_read_state21 == 1'b1) & (stream_in_24_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state22_io = ((ap_predicate_op239_write_state22 == 1'b1) & (stream_out_32_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state22_pp4_stage3_iter0 = (((ap_predicate_op239_write_state22 == 1'b1) & (stream_out_32_TREADY_int_regslice == 1'b0)) | ((ap_predicate_op223_read_state22 == 1'b1) & (stream_in_24_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_state23_io = ((last_reg_421 == 1'd0) & (stream_out_32_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state23_pp4_stage0_iter1 = ((last_reg_421 == 1'd0) & (stream_out_32_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state24_io = ((last_reg_421_pp4_iter1_reg == 1'd0) & (stream_out_32_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state24_pp4_stage1_iter1 = ((last_reg_421_pp4_iter1_reg == 1'd0) & (stream_out_32_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state25_io = ((last_reg_421_pp4_iter1_reg == 1'd0) & (stream_out_32_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state25_pp4_stage2_iter1 = ((last_reg_421_pp4_iter1_reg == 1'd0) & (stream_out_32_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter0 = (stream_in_24_TVALID_int_regslice == 1'b0);
end

always @ (*) begin
    ap_block_state4_pp0_stage1_iter0 = ((stream_out_32_TREADY_int_regslice == 1'b0) | (stream_in_24_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter1 = (stream_out_32_TREADY_int_regslice == 1'b0);
end

always @ (*) begin
    ap_block_state7_pp1_stage0_iter0 = (stream_in_24_TVALID_int_regslice == 1'b0);
end

always @ (*) begin
    ap_block_state8_pp1_stage1_iter0 = ((stream_out_32_TREADY_int_regslice == 1'b0) | (stream_in_24_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state9_pp1_stage0_iter1 = (stream_out_32_TREADY_int_regslice == 1'b0);
end

always @ (*) begin
    ap_condition_1536 = ((1'b1 == ap_CS_fsm_pp2_stage0) & (ap_phi_mux_delayed_last_1_phi_fu_213_p4 == 1'd0) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001));
end

always @ (*) begin
    ap_condition_1540 = ((delayed_last_1_reg_209 == 1'd0) & (1'b1 == ap_CS_fsm_pp2_stage1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage1_11001));
end

always @ (*) begin
    ap_condition_1545 = ((delayed_last_1_reg_209 == 1'd0) & (1'b1 == ap_CS_fsm_pp2_stage2) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage2_11001));
end

always @ (*) begin
    ap_condition_1549 = ((ap_enable_reg_pp4_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0) & (ap_phi_mux_delayed_last_phi_fu_413_p4 == 1'd0) & (1'b0 == ap_block_pp4_stage0_11001));
end

always @ (*) begin
    ap_condition_1553 = ((ap_enable_reg_pp4_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage1) & (delayed_last_reg_409 == 1'd0) & (1'b0 == ap_block_pp4_stage1_11001));
end

always @ (*) begin
    ap_condition_1558 = ((ap_enable_reg_pp4_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage2) & (delayed_last_reg_409 == 1'd0) & (1'b0 == ap_block_pp4_stage2_11001));
end

always @ (*) begin
    ap_condition_567 = ((1'b1 == ap_CS_fsm_pp2_stage0) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001));
end

always @ (*) begin
    ap_condition_795 = ((1'b1 == ap_CS_fsm_pp2_stage1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage1_11001));
end

always @ (*) begin
    ap_condition_806 = ((1'b1 == ap_CS_fsm_pp2_stage2) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage2_11001));
end

always @ (*) begin
    ap_condition_820 = ((1'b1 == ap_CS_fsm_pp2_stage3) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage3_11001));
end

always @ (*) begin
    ap_condition_843 = ((ap_enable_reg_pp4_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0) & (1'b0 == ap_block_pp4_stage0_11001));
end

always @ (*) begin
    ap_condition_850 = ((ap_enable_reg_pp4_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage1) & (1'b0 == ap_block_pp4_stage1_11001));
end

always @ (*) begin
    ap_condition_863 = ((ap_enable_reg_pp4_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage2) & (1'b0 == ap_block_pp4_stage2_11001));
end

always @ (*) begin
    ap_condition_876 = ((ap_enable_reg_pp4_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage3) & (1'b0 == ap_block_pp4_stage3_11001));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign ap_enable_pp2 = (ap_idle_pp2 ^ 1'b1);

assign ap_enable_pp3 = (ap_idle_pp3 ^ 1'b1);

assign ap_enable_pp4 = (ap_idle_pp4 ^ 1'b1);

assign ap_phi_reg_pp2_iter0_data_V_8_3_reg_332 = 'bx;

assign ap_phi_reg_pp2_iter0_last_6_0_reg_234 = 'bx;

assign ap_phi_reg_pp2_iter0_last_6_1_reg_268 = 'bx;

assign ap_phi_reg_pp2_iter0_last_6_2_reg_301 = 'bx;

assign ap_phi_reg_pp2_iter0_last_6_3_reg_359 = 'bx;

assign ap_phi_reg_pp2_iter0_user_6_3_reg_346 = 'bx;

assign ap_phi_reg_pp4_iter0_buffer_V_3_3_reg_587 = 'bx;

assign ap_phi_reg_pp4_iter0_has_last_V_3_3_reg_575 = 'bx;

assign ap_phi_reg_pp4_iter0_has_user_V_3_3_reg_563 = 'bx;

assign ap_phi_reg_pp4_iter0_last_2_0_reg_434 = 'bx;

assign ap_phi_reg_pp4_iter0_last_2_1_reg_478 = 'bx;

assign ap_phi_reg_pp4_iter0_last_2_2_reg_522 = 'bx;

assign ap_phi_reg_pp4_iter0_last_2_3_reg_599 = 'bx;

always @ (*) begin
    ap_predicate_op111_read_state10 = ((ap_phi_mux_last_4_phi_fu_226_p4 == 1'd0) & (ap_phi_mux_delayed_last_1_phi_fu_213_p4 == 1'd0));
end

always @ (*) begin
    ap_predicate_op123_read_state11 = ((last_6_0_reg_234 == 1'd0) & (delayed_last_1_reg_209 == 1'd0));
end

always @ (*) begin
    ap_predicate_op135_read_state12 = ((last_6_1_reg_268 == 1'd0) & (delayed_last_1_reg_209 == 1'd0));
end

always @ (*) begin
    ap_predicate_op147_read_state13 = ((last_6_2_reg_301 == 1'd0) & (delayed_last_1_reg_209 == 1'd0));
end

always @ (*) begin
    ap_predicate_op159_write_state13 = ((last_4_reg_221 == 1'd0) & (delayed_last_1_reg_209 == 1'd0));
end

always @ (*) begin
    ap_predicate_op183_read_state19 = ((ap_phi_mux_last_phi_fu_426_p4 == 1'd0) & (ap_phi_mux_delayed_last_phi_fu_413_p4 == 1'd0));
end

always @ (*) begin
    ap_predicate_op197_read_state20 = ((last_2_0_reg_434 == 1'd0) & (delayed_last_reg_409 == 1'd0));
end

always @ (*) begin
    ap_predicate_op210_read_state21 = ((last_2_1_reg_478 == 1'd0) & (delayed_last_reg_409 == 1'd0));
end

always @ (*) begin
    ap_predicate_op223_read_state22 = ((last_2_2_reg_522 == 1'd0) & (delayed_last_reg_409 == 1'd0));
end

always @ (*) begin
    ap_predicate_op239_write_state22 = ((last_reg_421 == 1'd0) & (delayed_last_reg_409 == 1'd0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_fu_615_p4 = {{stream_in_24_TDATA_int_regslice[15:8]}};

assign grp_fu_625_p4 = {{stream_in_24_TDATA_int_regslice[23:16]}};

assign grp_fu_635_p1 = stream_in_24_TLAST_int_regslice;

assign grp_read_fu_156_p2 = mode_0_data_reg;

assign or_ln107_fu_664_p2 = (stream_in_24_TUSER_int_regslice | empty_38_reg_1082_3);

assign or_ln70_1_fu_809_p2 = (stream_in_24_TUSER_int_regslice | ap_phi_reg_pp2_iter0_user_6_1_reg_290);

assign or_ln70_2_fu_835_p2 = (stream_in_24_TUSER_int_regslice | ap_phi_reg_pp2_iter0_user_6_2_reg_322);

assign or_ln70_fu_783_p2 = (stream_in_24_TUSER_int_regslice | ap_phi_reg_pp2_iter0_user_6_0_reg_256);

assign or_ln90_fu_744_p2 = (stream_in_24_TUSER_int_regslice | empty_36_reg_1117_3);

assign out_c1_V_fu_678_p2 = (zext_ln358_1_fu_674_p1 + zext_ln358_fu_671_p1);

assign out_c2_V_fu_691_p2 = (zext_ln358_3_fu_687_p1 + zext_ln358_2_fu_684_p1);

assign p_Result_11_fu_767_p5 = {{data_V_8_3_reg_332[31:8]}, {trunc_ln674_2_fu_763_p1}};

assign p_Result_14_fu_859_p3 = {{alpha_read_reg_1073}, {stream_in_24_TDATA_int_regslice}};

assign p_Result_15_fu_721_p5 = {{{{p_Result_9_fu_711_p4}, {trunc_ln674_1_fu_707_p1}}, {p_Result_8_fu_697_p4}}, {trunc_ln674_reg_1097}};

assign p_Result_1_fu_899_p5 = {{ap_phi_reg_pp4_iter0_buffer_V_3_0_reg_467[95:48]}, {stream_in_24_TDATA_int_regslice}, {ap_phi_reg_pp4_iter0_buffer_V_3_0_reg_467[23:0]}};

assign p_Result_2_fu_931_p5 = {{ap_phi_reg_pp4_iter0_buffer_V_3_1_reg_511[95:72]}, {stream_in_24_TDATA_int_regslice}, {ap_phi_reg_pp4_iter0_buffer_V_3_1_reg_511[47:0]}};

assign p_Result_34_1_fu_793_p5 = {{ap_phi_reg_pp2_iter0_data_V_8_0_reg_245[31:16]}, {trunc_ln674_3_fu_789_p1}, {ap_phi_reg_pp2_iter0_data_V_8_0_reg_245[7:0]}};

assign p_Result_34_2_fu_819_p5 = {{ap_phi_reg_pp2_iter0_data_V_8_1_reg_279[31:24]}, {trunc_ln674_4_fu_815_p1}, {ap_phi_reg_pp2_iter0_data_V_8_1_reg_279[15:0]}};

assign p_Result_34_3_fu_846_p5 = {{trunc_ln674_5_fu_842_p1}, {ap_phi_reg_pp2_iter0_data_V_8_2_reg_312[23:0]}};

assign p_Result_36_1_fu_755_p3 = {{trunc_ln215_1_fu_751_p1}, {trunc_ln215_reg_1122}};

assign p_Result_3_fu_963_p5 = {{stream_in_24_TDATA_int_regslice}, {ap_phi_reg_pp4_iter0_buffer_V_3_2_reg_553[71:0]}};

assign p_Result_8_fu_697_p4 = {{out_c1_V_fu_678_p2[8:1]}};

assign p_Result_9_fu_711_p4 = {{out_c2_V_fu_691_p2[8:1]}};

assign p_Result_s_fu_867_p5 = {{buffer_V_3_3_reg_587[95:24]}, {stream_in_24_TDATA_int_regslice}};

assign stream_in_24_TREADY = regslice_both_stream_in_24_V_data_V_U_ack_in;

assign stream_out_32_TVALID = regslice_both_stream_out_32_V_data_V_U_vld_out;

assign tmp_1_fu_889_p4 = {has_last_V_3_3_reg_575[4-1:1], |(stream_in_24_TLAST_int_regslice)};

assign tmp_2_fu_911_p4 = {ap_phi_reg_pp4_iter0_has_user_V_3_0_reg_445[4 - 1:2], |(stream_in_24_TUSER_int_regslice), ap_phi_reg_pp4_iter0_has_user_V_3_0_reg_445[0:0]};

assign tmp_3_fu_921_p4 = {ap_phi_reg_pp4_iter0_has_last_V_3_0_reg_456[4 - 1:2], |(stream_in_24_TLAST_int_regslice), ap_phi_reg_pp4_iter0_has_last_V_3_0_reg_456[0:0]};

assign tmp_4_fu_943_p4 = {ap_phi_reg_pp4_iter0_has_user_V_3_1_reg_489[4 - 1:3], |(stream_in_24_TUSER_int_regslice), ap_phi_reg_pp4_iter0_has_user_V_3_1_reg_489[1:0]};

assign tmp_5_fu_953_p4 = {ap_phi_reg_pp4_iter0_has_last_V_3_1_reg_500[4 - 1:3], |(stream_in_24_TLAST_int_regslice), ap_phi_reg_pp4_iter0_has_last_V_3_1_reg_500[1:0]};

assign tmp_6_fu_976_p4 = {|(stream_in_24_TUSER_int_regslice), ap_phi_reg_pp4_iter0_has_user_V_3_2_reg_533[3 - 1:0]};

assign tmp_7_fu_987_p4 = {|(stream_in_24_TLAST_int_regslice), ap_phi_reg_pp4_iter0_has_last_V_3_2_reg_543[3 - 1:0]};

assign tmp_fu_879_p4 = {has_user_V_3_3_reg_563[4-1:1], |(stream_in_24_TUSER_int_regslice)};

assign trunc_ln215_1_fu_751_p1 = stream_in_24_TDATA_int_regslice[15:0];

assign trunc_ln215_fu_733_p1 = stream_in_24_TDATA_int_regslice[15:0];

assign trunc_ln674_1_fu_707_p1 = stream_in_24_TDATA_int_regslice[7:0];

assign trunc_ln674_2_fu_763_p1 = stream_in_24_TDATA_int_regslice[7:0];

assign trunc_ln674_3_fu_789_p1 = stream_in_24_TDATA_int_regslice[7:0];

assign trunc_ln674_4_fu_815_p1 = stream_in_24_TDATA_int_regslice[7:0];

assign trunc_ln674_5_fu_842_p1 = stream_in_24_TDATA_int_regslice[7:0];

assign trunc_ln674_6_fu_998_p1 = ap_phi_mux_buffer_V_3_3_phi_fu_591_p4[31:0];

assign trunc_ln674_fu_653_p1 = stream_in_24_TDATA_int_regslice[7:0];

assign zext_ln358_1_fu_674_p1 = grp_fu_615_p4;

assign zext_ln358_2_fu_684_p1 = p_Result_5_reg_1092;

assign zext_ln358_3_fu_687_p1 = grp_fu_625_p4;

assign zext_ln358_fu_671_p1 = p_Result_s_40_reg_1087;

endmodule //pixel_pack
